site_name: NetMQ

pages:
- ['index.md', 'Home']
- ['intro/getting-started.md', 'Introduction', 'Getting Started']
- ['intro/philosophy.md', 'Introduction', 'Philosophy']
- ['intro/example.md', 'Introduction', 'Example']
